name: grocery
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.0
  firebase_core: ^2.18.0
  firebase_auth: ^4.16.0
  carousel_slider: ^4.1.1
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.2.1
  badges: ^3.1.2
  flutter_zoom_drawer: ^3.1.1
  provider: ^6.1.5
  geolocator: ^14.0.0
  geocoding: ^2.2.0
  permission_handler: ^11.3.0
  intl_phone_field: ^3.2.0
  google_maps_flutter: ^2.5.0
  image_picker: ^1.0.4
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  easy_localization: ^3.0.7+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/emptycart.webp
    - assets/images/refer.jpg
    - assets/translation/
    
